// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa-oataJfx9z6h5Omh6FTQDZCfbSjMlYw',
    appId: '1:462394857537:android:ba1792ff0d3cbadc9ccec0',
    messagingSenderId: '462394857537',
    projectId: 'visa-assist-c9d42',
    storageBucket: 'visa-assist-c9d42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBwpNyYyb2GRvKDOyXPreFgT2YLoaSOgI',
    appId: '1:462394857537:ios:29f7af557347730c9ccec0',
    messagingSenderId: '462394857537',
    projectId: 'visa-assist-c9d42',
    storageBucket: 'visa-assist-c9d42.firebasestorage.app',
    androidClientId: '462394857537-3e7ou0a84t7ndgngjb77hptujicsd93h.apps.googleusercontent.com',
    iosClientId: '462394857537-pdfeb2ga4vucbn4nvgfpp9ijqijr1oe8.apps.googleusercontent.com',
    iosBundleId: 'com.example.visaApp',
  );
}
